import react from "react";
import { StyleSheet } from "react-native";
const ButtonStyles = StyleSheet.create({
  buttonSignUp: {
    fontSize: 12,
    borderRadius: 5,
    height: 30,
    width: 300,
    backgroundColor: "#083464",
    overflow: "hidden",
    borderColor: "yellow",
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    marginBottom: 5,
  },
  buttonLogin: {
    borderRadius: 5,
    height: 30,
    width: 300,
    backgroundColor: "#fff",
    overflow: "hidden",
    borderColor: "#FFA611",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 35,
  },
  listButtons: {
    borderRadius: 5,
    height: 30,
    width: 100,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#083464",
    overflow: "hidden",
    // borderColor: "yellow",
    borderWidth: 2,

    marginTop: 2,
    marginBottom: 5,
  },
  deleteButtons: {
    borderRadius: 5,
    height: 30,
    width: 100,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "red",
    overflow: "hidden",
    borderColor: "red",
    borderWidth: 2,

    marginTop: 2,
    marginBottom: 5,
  },
  disabledButton: {
    paddingVertical: 5,
    height: 30,
    width: 100,
    alignItems: "center",
    backgroundColor: "gray",
    borderColor: "gray",
    borderWidth: 1,
    borderRadius: 5,
  },
  listText: {
    fontSize: 20,
    // fontWeight: "bold",
    color: "#001a34",
    padding: 3,
  },
  smallListText: {
    fontSize: 15,
    // fontWeight: "bold",
    color: "#001a34",
    padding: 3,
    fontStyle: "italic",
  },
  Title: {
    fontSize: 23,
    fontWeight: "bold",
    color: "yellow",
    padding: 3,
    justifyContent: "center",
    alignItems: "center",
  },
});
export default ButtonStyles;
